export const GET_CATEGORY_LIST_START = 'GET_CATEGORY_LIST_START'
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const GET_CATEGORY_LIST_FAILED = 'GET_CATEGORY_LIST_FAILED'