export const GET_PRODUCTS_START = 'GET_PRODUCTS_START'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const SET_PRODUCT_TO_CARD = 'SET_PRODUCT_TO_CARD'
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'

export const PRODUCT_COUNT_PLUS = 'PRODUCT_COUNT_PLUS'
export const PRODUCT_COUNT_MINUS = 'PRODUCT_COUNT_MINUS'